import {
  AlignLeft,
  AtSign,
  Calendar,
  CalendarClock,
  CheckSquare,
  ChevronDownSquare,
  CircleDot,
  Clock,
  FileUp,
  Gauge,
  Hash,
  Heading,
  Link,
  ListChecks,
  type LucideIcon,
  Minus,
  PenLine,
  Phone,
  Rows3,
  Star,
  Text,
  ThumbsUp,
  Type,
  SlidersHorizontal,
} from "lucide-react";
import type { FieldType } from "@/types/forms";

export const FIELD_ICONS: Record<FieldType, LucideIcon> = {
  short_text: Type,
  long_text: AlignLeft,
  email: AtSign,
  phone: Phone,
  number: Hash,
  url: Link,
  dropdown: ChevronDownSquare,
  radio: CircleDot,
  checkbox: CheckSquare,
  multi_select: ListChecks,
  date: Calendar,
  time: Clock,
  datetime: CalendarClock,
  rating: Gauge,
  star_rating: Star,
  yes_no: ThumbsUp,
  linear_scale: SlidersHorizontal,
  file_upload: FileUp,
  signature: PenLine,
  heading: Heading,
  paragraph: Text,
  divider: Minus,
  section: Rows3,
};
